package BMICalculatorApp;


/**
* BMICalculatorApp/BMICalculatorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bmicalculator.idl
* Thursday, October 4, 2018 12:29:59 AM BRT
*/

public abstract class BMICalculatorPOA extends org.omg.PortableServer.Servant
 implements BMICalculatorApp.BMICalculatorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calculateBMI", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BMICalculatorApp/BMICalculator/calculateBMI
       {
         double height = in.read_double ();
         double weight = in.read_double ();
         double $result = (double)0;
         $result = this.calculateBMI (height, weight);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BMICalculatorApp/BMICalculator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BMICalculator _this() 
  {
    return BMICalculatorHelper.narrow(
    super._this_object());
  }

  public BMICalculator _this(org.omg.CORBA.ORB orb) 
  {
    return BMICalculatorHelper.narrow(
    super._this_object(orb));
  }


} // class BMICalculatorPOA
