package BMICalculatorApp;


/**
* BMICalculatorApp/BMICalculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bmicalculator.idl
* Saturday, February 25, 2023 12:30:22 PM CET
*/

public interface BMICalculator extends BMICalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BMICalculator
