package BMICalculatorApp;


/**
* BMICalculatorApp/BMICalculatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bmicalculator.idl
* Sunday, February 26, 2023 12:29:46 PM CET
*/

abstract public class BMICalculatorHelper
{
  private static String  _id = "IDL:BMICalculatorApp/BMICalculator:1.0";

  public static void insert (org.omg.CORBA.Any a, BMICalculatorApp.BMICalculator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BMICalculatorApp.BMICalculator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BMICalculatorApp.BMICalculatorHelper.id (), "BMICalculator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BMICalculatorApp.BMICalculator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BMICalculatorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BMICalculatorApp.BMICalculator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BMICalculatorApp.BMICalculator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BMICalculatorApp.BMICalculator)
      return (BMICalculatorApp.BMICalculator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BMICalculatorApp._BMICalculatorStub stub = new BMICalculatorApp._BMICalculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BMICalculatorApp.BMICalculator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BMICalculatorApp.BMICalculator)
      return (BMICalculatorApp.BMICalculator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BMICalculatorApp._BMICalculatorStub stub = new BMICalculatorApp._BMICalculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
