package BMICalculatorApp;


/**
* BMICalculatorApp/BMICalculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bmicalculator.idl
* Thursday, October 4, 2018 12:29:59 AM BRT
*/

public interface BMICalculator extends BMICalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BMICalculator
