module BMICalculatorApp {
    interface BMICalculator {
        double calculateBMI(in double height, in double weight);
        double calculateTMB(in double height, in double weight, in double age);
        double calculateTMBf(in double height, in double weight, in double age);
    };
};
